### ISSUE TITLE
query of title, twitter fails: bug in Helper.to_tuple_lst parsing?

### ISSUE THREAD

**Issue by carlos-molina** [yansh/MoanaML#19] opened 2015-06-15 22:09 UTC
Yans,

it seems that 
let _ = Helper.StringMap.iter Helper.print_var r_map

can correctly handle queries of fn, last, email and image, but fails with title and twitter. 

The intriguing fact is that it never fails when the contact's first name is Jon.  

It seems to me that the function Helper.to_tuple_lst can't filter out some of the spaces and invisible chars.  

See some of the outputs and let me know if you are aware of the that.

Cheers,

Carlos

 <h2>Right output of Carlos' fn, last, email, image, mobile </h2>

1) My three input parameters

let q1 =
  "MAP {
         ?y, canView,?x, policies
         ?x, ?anypred, ?anyobj, contacts
        }"

let q2 =
  "MAP {
        ?y,fn,Carlos,contacts
        ?y,last,?last,contacts
        ?y,email,?email,contacts
        ?y,image,?image,contacts
        ?y,mobile,?mobile,contacts
        }"

let r_map = Rete.get_res_map results ["?y"; "?fn"; "?last"; "?email"; "?image"; "?mobile"]

2) Right output

% contacts.byte
?email
cm770@cam.ac.uk
?image
carlos.jpg
?last
Molina-jimenez
?y
d

 <h2> Wrong output of Carlos' twitter </h2>

1) My threee input parameters

let q1 =
  "MAP {
         ?y, canView,?x, policies
         ?x, ?anypred, ?anyobj, contacts
        }"

let q2 =
  "MAP {
        ?y,fn,Carlos,contacts
        ?y,last,?last,contacts
        ?y,email,?email,contacts
        ?y,image,?image,contacts
        ?y,mobile,?mobile,contacts
        ?y,twitter,?twitter,contacts
        }"

let r_map = Rete.get_res_map results ["?y"; "?fn"; "?last"; "?email"; "?image"; "?mobile"; "?twitter"]

2) Wrong output

bash-3.2$ contacts.byte
?email
cm770@cam.ac.uk
?image
carlos.jpg
?last
Molina-jimenez
?twitter
@mort__
@carlos
@avsm
@amirmc
@tforcworc
?y
a
b
c
d
e

 <h2> Wrong output of Carlos' title </h2>

1) My three input parameters

let q1 =
  "MAP {
         ?y, canView,?x, policies
         ?x, ?anypred, ?anyobj, contacts
        }"

let q2 =
  "MAP {
        ?y,fn,Carlos,contacts
        ?y,last,?last,contacts
        ?y,email,?email,contacts
        ?y,image,?image,contacts
        ?y,mobile,?mobile,contacts
        ?y,title,?title,contacts
        }"

let r_map = Rete.get_res_map results ["?y"; "?fn"; "?last"; "?email"; "?image"; "?mobile"; "?title"]

2) My output

bash-3.2$ contacts.byte
?email
cm770@cam.ac.uk
?image
carlos.jpg
?last
Molina-jimenez
?title
Lecturer
Postdoc
Lecturer
Postdoc
Professor
?y
a
b
c
d
e

<h2>Right output of Jon's fn, last, email, image, title, twitter </h2>

1) My three input parameters

let q1 =
  "MAP {
         ?y, canView,?x, policies
         ?x, ?anypred, ?anyobj, contacts
        }"

let q2 =
  "MAP {
        ?y,fn,Jon,contacts
        ?y,last,?last,contacts
        ?y,email,?email,contacts
        ?y,image,?image,contacts
        ?y,mobile,?mobile,contacts
        ?y,title,?title,contacts
        ?y,twitter,?twitter,contacts
        }"

let r_map = Rete.get_res_map results ["?y"; "?fn"; "?last"; "?email"; "?image"; "?mobile"; "?title"; "?twitter"]

2) Right output

bash-3.2$ contacts.byte
?email
jon.crowcroft@cl.cam.ac.uk
?image
jon.jpg
?last
Crowcroft
?mobile
 617-000-0001
?title
Professor
?twitter
@tforcworc
?y
a

**Comment by carlos-molina** [comment] 2015-06-17 17:26
Yan

I downloaded the latest version. The bug is still there. I get the same incorrect outputs.

It seems that the parser can't handle some of the invisible chars included in image, title and twitter of Carlos, Amir and Anil. 

It might help to see the two independent outputs shown below: The first one is right. The second one includes anil.jpg twice. 

Carlos
--------------------------------------------------------------------------------------------

$ contacts.byte
?email
cm770@cam.ac.uk
?image
carlos.jpg
?last
Molina-jimenez
?y
d

$ contacts.byte
?email
anil@recoil.org
anil.madhavapeddy@recoil.org
?image
anil.jpg
anil.jpg
?last
Madhavapeddy
?y
c
c

**Comment by carlos-molina** [comment] 2015-06-17 17:33
I'll focus on fn, last and email and have a look at the parser at some point.

Carlos

**Comment by yansh** [comment] 2015-07-01 14:25
Ok, it's not the parser. The problem is the current implementation doesn't handle well missing attributes. In your query your have "?y,mobile,?mobile,contacts" which doesn't exist when you query for tuples associated with "Carlos".  The wrong output is a result of a bug and needs to be fixed.

**Comment by carlos-molina** [comment] 2015-07-01 14:28
Good and thanks for letting me know.

Do you have any ref to the rete algorithm you implemented? I will help me to understand a bit the Ocaml code.

Carlos

**Comment by yansh** [comment] 2015-07-02 20:51
I fixed the behavior, now it should work correctly. Note that the correct response to your query is empty graph because the tuple template with mobile attribute doesn't exist for you. Essentially, since you chose to refine your query you get an exact mapping back, once you add a tuple the __mobile__ attribute  then it will return the result you are after.

**Comment by carlos-molina** [comment] 2015-07-02 21:45
Good, thanks a lot Yan. Let me run some tests!

**Comment by carlos-molina** [comment] 2015-07-14 21:02
Yan,

it seems that there is a bug in contacts.ml: there is no policy in the function results as q2 (the query) is used as a policy as well.

let q2 =
"MAP {
?y,fn,Carlos,contacts
?y,last,?last,contacts
?y,email,?email,contacts
?y,image,?image,contacts
?y,twitter,?twitter,contacts
}"

let results = (ReteImpl.InMemory.exec_qry q2 (List.flatten contacts)) |> (ReteImpl.InMemory.exec_bm q2)

% contacts.byte 
(*only output from  let _ = Helper.StringMap.iter Helper.print_var r_map  is shown *)
?email
cm770@cam.ac.uk
?image
carlos.jpg
?last
Molina-jimenez
?twitter
@carlos
?y
d

If you use a policy, for ex q1 (or anything else), you get an empty result

let q1 =
"MAP {
?y, canView,?x, policies
?x, ?anypred, ?anyobj, contacts
}"

  % contacts.byte
(*only output from  let _ = Helper.StringMap.iter Helper.print_var r_map  is shown *)
      --
        ---------------------------------
      --

**Comment by yansh** [comment] 2015-07-15 00:12
Well spotted...

You need to add tuples for policies

> let results = (ReteImpl.InMemory.exec_qry q1 (List.flatten (contacts @ [policies]))) |> (ReteImpl.InMemory.exec_bm q2)

I am testing, so will update code later

**Comment by yansh** [comment] 2015-08-07 17:09
Closing, seems to work.

**Closed as completed by yansh** 2015-08-07 17:09 UTC
Labels: bug
